config/routes.rb
Rails.application.routes.draw do
  get 'imports/index'

  authenticate :user do
    resources :albums
    resources :entries
    resources :imports, only: [:index, :create]
    
    get "/tagged/:tag_name", to: "entries#index", as: :tagged_with
    resources :tags, only: :index

    root 'albums#index'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:sessions, :registrations]
  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    # get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    # post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update",  as: :update_user_registration
    get    "account" => "devise/registrations#edit",    as: :edit_user_registration
    delete "account" => "devise/registrations#destroy", as: :destroy_user_registration
  end
end

app/views/elements/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= alert_mapping[key] %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/elements/_modal.html.erb
<div id="modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content container-fluid">
      
    </div>
  </div>
</div>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to defined?(root_path) ? root_path : "#", class: "navbar-brand" do %>
      <%= icon "cloud-upload" %>
      Gifantry
    <% end %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li>
        <a href="#" id="clickable">Drag and drop to upload!</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= render "elements/search" %>
      </li>

      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to edit_user_registration_path do %>
                  <span class="fa fa-user"></span>
                  Edit Account
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="fa fa-sign-out"></span>
                  Sign Out
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <% if devise_mapping.registerable? %>
            <!-- <li><%#= link_to "Sign Up", new_user_registration_path %></li> -->
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/elements/_progress_bar.html.erb
<div id="progress-bar" class="hide">
  <div class="progress">
    <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
    </div>
  </div>
</div>

app/views/elements/_search.html.erb
<%= form_tag "/entries", method: :get, id: "search-form" do %>
  <div class="input-group">
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for stuff", aria_describedby: "search-addon", autofocus: true %>
    <span id="search-addon" class="input-group-addon">
      <%= icon "search" %>
    </span>
  </div>
<% end %>

app/views/elements/_sidenav.html.erb
<div id="sidenav" class="col-sm-2 form-group">
  <ul class="nav nav-stacked nav-pills">
    <li>
      <div class="row form-group">
        <div class="col-xs-6">
          <%= link_to new_album_path, class: "btn btn-default btn-sm btn-block", data: { toggle: "modal", target: "#modal" } do %>
            <span class="fa fa-plus-square"></span>
            Album
          <% end %>
        </div>

        <div class="col-xs-6">
          <%= link_to imports_path(album_id: @album.try(:id)), class: "btn btn-default btn-sm btn-block", data: { toggle: "modal", target: "#modal" } do %>
            <span class="fa fa-upload"></span>
            Import
          <% end %>
        </div>
      </div>
    </li>

    <% if params[:tag_name].present? %>
      <li role="presentation" class="<%= "active" if params[:id].nil? %>">
        <a href="/">
          Tag: <%= params[:tag_name] %>
          <div class="badge pull-right">
            <%= @entries.count %>
          </div>
        </a>
      </li>
    <% end %>

    <li role="presentation" class="<%= "active" if @album.nil? %>">
      <a href="/">
        All
        <div class="badge pull-right">
          <%= current_user.entries.count %>
        </div>
      </a>
    </li>

    <%= render @albums %>
  </ul>
</div>