config/routes.rb
Rails.application.routes.draw do
  get 'imports/index'

  authenticate :user do
    resources :albums
    resources :entries
    resources :imports, only: [:index, :create]
    
    get "/tagged/:tag_name", to: "entries#index", as: :tagged_with
    resources :tags, only: :index

    root 'albums#index'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:sessions, :registrations]
  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    # get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    # post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update",  as: :update_user_registration
    get    "account" => "devise/registrations#edit",    as: :edit_user_registration
    delete "account" => "devise/registrations#destroy", as: :destroy_user_registration
  end
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  description        :text0
#  image_file_name    :string(255)
#  image_file_size    :integer
#  image_content_type :string(255)
#  album_id           :integer
#  created_at         :datetime
#  updated_at         :datetime
#

class Entry < ActiveRecord::Base
  VIEWS = { list: "list", grid: "grid" }
  VIEWS.default = VIEWS[:grid]

  belongs_to :album, counter_cache: true
  belongs_to :user, counter_cache: true
  scope :sorted, -> { order "entries.created_at DESC" }

  has_attached_file :image
  validates_attachment_content_type :image, content_type: [
    "image/jpeg", "image/pjpeg", "image/jpg", "image/png", "image/gif", "image/gifv"
  ]
  acts_as_taggable

  include PgSearch
  pg_search_scope :search,
    against: {
      image_file_name: 'B',
      name: 'C',
      description: 'D'
    },
    associated_against: {
      tags: [:name],
      album: [:name]
    },
    using: {
      tsearch: {
        dictionary: "english",
        prefix: true,
        any_word: true
      }
    }

  def display_name
    name || image_file_name
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :set_entry_view, only: :index

  def index
    @albums = current_user.albums
    @entries = get_entries
    @entry = Entry.new
  end

  def show
    render layout: "modal_layout"
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def detail
    render layout: "modal_layout"
  end

  def create
    @entry = current_user.entries.build entry_params

    respond_to do |format|
      if @entry.save!
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json do
          render json: { error: @entry.errors.full_messages }, status: :unprocessable_entity
        end
      end
    end
  rescue => e
    render json: { error: e.message }, status: :server_error
  end

  def update
    respond_to do |format|
      if @entry.update entry_params
        format.html { redirect_to album_path(@entry.album.slug), notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    name = @entry.display_name
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to :back, notice: "The Entry \"#{name}\" was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_entry
    @entry = current_user.entries.find params[:id]
  end

  def entry_params
    params.require(:entry).permit(
      :name,
      :description,
      :image,
      :album_id,
      :tag_list
    )
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>" class="entry thumbnail">
  <%= link_to entry_path(entry), data: { toggle: "modal", target: "#modal" } do %>
    <%= image_tag entry.image.url %>
  <% end %>

  <div id="modal_<%= dom_id entry %>" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
  </div>
</div>

app/views/entries/_form.html.erb
<% @entry ||= entry %>

<%= form_for @entry, multipart: true, html: { class: 'form-horizontal dropzone' } do |f| %>
  <div class="row">
    <div class="col-sm-5">
      <div class="form-group">
        <%= f.label :album_id, class: 'control-label col-md-2' %>
        <div class="col-md-10">
          <%= f.collection_select :album_id, Album.all, :id, :name, {}, { class: 'text-field form-control' } %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :image, class: 'control-label col-md-2' %>
        <div class="col-md-10">
          <%= f.file_field :image, class: 'text-field form-control', multiple: true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :name, class: 'control-label col-md-2' %>
        <div class="col-md-10">
          <%= f.text_field :name, rows: 3, class: 'text-field form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :description, class: 'control-label col-md-2' %>
        <div class="col-md-10">
          <%= f.text_area :description, rows: 3, class: 'text-field form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :tag_list, "Tags", class: 'control-label col-md-2' %>
        <div class="col-md-10">
          <%= f.text_field :tag_list, value: @entry.tag_list.join(", "), class: 'text-field form-control token-input' %>
        </div>
      </div>
    </div>

    <div id="form-image" class="col-sm-7 form-group">
      <%= image_tag @entry.image.url %>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
        <%= f.submit nil, class: "btn btn-primary" %>
        <%= link_to "Cancel", :back, class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/entries/_grid.html.erb
<div id="entries-container" class="col-sm-10">
  <div class="grid">
    <div id="dropzone-queue" class="dropzone-previews"></div>

    <% if @entries.empty? %>
      <p class="text-center">Drag something here to upload!</p>
    <% else %>
      <%= render "entries/toolbar" %>

      <div id="infinite-entries">
        <%= render partial: "entries/grid_item", collection: @entries %>
      </div>

      <div class="pagination pull-right">
        <%= paginate @entries %>
      </div>
    <% end %>
  </div>
</div>

app/views/entries/_grid_item.html.erb
<div id="<%= dom_id grid_item %>" class="entry thumbnail">
  <%= link_to entry_path(grid_item), data: { toggle: "modal", target: "#modal" } do %>
    <%= image_tag grid_item.image.url %>
  <% end %>

  <div id="modal_<%= dom_id grid_item %>" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
  </div>
</div>

app/views/entries/_list.html.erb
<div id="entries-list" class="col-sm-10">
  <div id="dropzone-queue" class="dropzone-previews"></div>

  <% if @entries.empty? %>
    <p class="text-center">Drag something here to upload!</p>
  <% else %>
    <div id="toolbar" class="form-group clearfix">
      <div class="btn-group pull-right ">
        <%= link_to icon("download"), "#", class: "btn btn-xs btn-default", title: "Download all" %>
      </div> 
      
      <div class="btn-group pull-right m-right-7">
        <%= link_to icon("list"), "#", class: "btn btn-xs btn-default", title: "List View", data: { view: "list" } %>
        <%= link_to icon("th"), "#", class: "btn btn-xs btn-default", title: "Grid View", data: { view: "grid" } %>
      </div>     
    </div>

    <div id="infinite-entries">
      <%= render @entries %>
    </div>

    <p class="pagination clearfix">
      <%= link_to_next_page @entries, "Next Page", remote: true %>
    </p>
  <% end %>
</div>

app/views/entries/_list_item.html.erb
<li id="<%= dom_id list_item %>" class="entry">
  <div class="row">
    <div class="col-xs-2">
      <div class="thumbnail">
        <%= image_tag list_item.image.url %>
      </div>
    </div>

    <div class="col-xs-8">
      <%= text_field_tag nil, list_item.image.url, class: "form-control select-text" %>
    </div>

    <div class="col-xs-2">
      <div class="btn-group pull-right">
        <%= link_to edit_entry_path(list_item), class: "btn btn-sm btn-primary" do %>
          <span class="fa fa-edit"></span>
          Edit
        <% end %>

        <%= link_to list_item, class: "btn btn-sm btn-danger", data: { method: :delete, confirm: "Are you sure you want to delete #{list_item.image_file_name}?" } do %>
          <span class="fa fa-remove"></span>
          Delete
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/entries/_new_entry.html.erb
<h1>Add Image</h1>
<%= render "entries/form", entry: Entry.new %>

app/views/entries/_toolbar.html.erb
<div id="toolbar" class="form-group clearfix">
  <div class="btn-group pull-right ">
    <%= link_to icon("download"), "#", class: "btn btn-xs btn-default", title: "Download all" %>
  </div> 
  
  <div class="btn-group pull-right m-right-7">
    <%= link_to icon("th"), "#", class: "btn btn-xs btn-default#{" active" if @entry_view == "grid"}", title: "Grid View", data: { view: "grid" } %>
    <%= link_to icon("list"), "#", class: "btn btn-xs btn-default#{" active" if @entry_view == "list"}", title: "List View", data: { view: "list" } %>
  </div>     
</div>

app/views/entries/edit.html.erb
<%- model_class = Entry -%>

<div class="col-sm-12">
  <h1>
    <%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: Entry %>
  </h1>
  <%= render "form" %>
</div>

app/views/entries/index.html.erb
<%= form_for @entry, multiple: true, html: { id: "entries", class: "dropzone col-sm-12" } do |f| %>
  <%= render "elements/sidenav" %>
  <%= render @entry_view %>
  <%= f.hidden_field :album_id, value: @album.try(:id) %>
<% end %>

app/views/entries/new.html.erb
<h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: Entry %></h1>
<%= render partial: 'form' %>

app/views/entries/show.html.erb
<% content_for :modal_title, funny_gif_titles.sample.html_safe %>

<figure class="entry-info">
  <div class="info form-group">
    <%= text_field_tag "#", @entry.image.url, class: "select-text" %>
  </div>

  <%= image_tag @entry.image.url %>

  <figcaption>
    <div class="info row fieldset">
      <dl class="col-sm-4">
        <dt class="label label-default">Album</dt>
        <dd>
          <pre class="prettyprint"><%= link_to_if @entry.album, @entry.album.try(:name) || "None", [:album, id: @entry.album.try(:slug)] %></pre>
        </dd>
      </dl>

      <dl class="col-sm-4">
        <dt class="label label-default">Size</dt>
        <dd>
          <pre class="prettyprint"><%= number_to_human_size @entry.image_file_size %></pre>
        </dd>
      </dl>

      <dl class="col-sm-4">
        <dt class="label label-default">Uploaded at</dt>
        <dd>
          <pre class="prettyprint"><%= I18n.l @entry.created_at %></pre>
        </dd>
      </dl>

      <% unless @entry.name.blank? %>
        <dl class="col-sm-12">
          <dt class="label label-default">Name</dt>
          <dd>
            <pre class="prettyprint"><%= @entry.name %></pre>
          </dd>
        </dl>
      <% end %>

      <% unless @entry.description.blank? %>
        <dl class="col-sm-12">
          <dt class="label label-default">Description</dt>
          <dd>
            <pre class="prettyprint"><%= @entry.description %></pre>
          </dd>
        </dl>
      <% end %>

      <% unless @entry.tags.empty? %>
        <dl class="col-sm-12">
          <dt class="label label-default">Tags</dt>
          <dd>
            <pre class="prettyprint"><%= render partial: "tags/tag", collection: @entry.tags, locals: { tags_count: @entry.tags.count } %></pre>
          </dd>
        </dl>
      <% end %>

      <hr>

      <div class="col-sm-6">
        <%= link_to edit_entry_path(@entry), class: "btn btn-sm btn-primary btn-block" do %>
          <span class="fa fa-edit"></span>
          Edit
        <% end %>
      </div>
      <div class="col-sm-6">
        <%= link_to @entry, class: "btn btn-sm btn-danger btn-block", data: { method: :delete, confirm: "Are you sure you want to delete #{@entry.image_file_name}?" } do %>
          <span class="fa fa-remove"></span>
          Delete
        <% end %>
      </div>
    </div>
  </figcaption>
</figure>